print("-----------------------------")
print("COCOFRESH SHOP")
print("-----------------------------")
print("")
print("MENU")
print("1.Smoothies Coconut")
print("2.Strawberry Smoothies Coconut")
print("3.Logan Smoothies Coconut")
print("4.Freshed Coconut")
print("5.CocaCola Coconut")
print("6.CocaCola")
print("7.Water")
print("8.Mineral Water")